### ISSUE TITLE
Issue 1: User can randomly generate a color palette

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/Pigment#1]
## 💰 Motivation

Artists/designers can select a randomly generated color palette to add to their project

## 📐 Plan

Create a responsive form that allows users to randomly generate a color palette and enter additional project details. 

## 🖼️ Wireframes
![Screen Shot 2022-08-01 at 12 53 00 PM](https://user-images.githubusercontent.com/106884008/182233567-ee2a172c-deeb-463f-8941-ed97beea49ec.png)
![Screen Shot 2022-08-01 at 12 54 14 PM](https://user-images.githubusercontent.com/106884008/182233772-240a22b3-f77f-4055-9bef-58b337b77779.png)
![Screen Shot 2022-08-01 at 12 54 25 PM](https://user-images.githubusercontent.com/106884008/182233798-e2b94abc-fffa-4bb8-82fb-b338d7bea916.png)

## ✅ Task List

- [x] Add a `div[data-view="new-project-form"]` to the HTML.
- [x] Add a form for creating anew journal entry to the `div[data-view="new-project-form"]`. Form includes: 
  - [x] Input for project name
  - [x] Input/textarea for project details 
  - [x] Input for project details (type = date)
  - [x] New palette button to generate a random color palette 
  - [x] Rectangles to hold the generated palette colors 
  - [x] A rectangle to hold the gradient of the colors 
  - [x] Save button  
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make all inputs of the journal entry form `required`.
- [x] Create a data model that includes:
  - [x] view: 'new-project-form'
  - [x] entries: []
  - [x] nextEntryId: 1
  - [x] current-palette-colors:
- [x] Send a network request to obtain the hex codes for the randomly generated color palette that will pre-populate the page. 
- [x]  Fill the rectangles, hex values, and the gradient accordingly with the generated hex codes.  
- [x]  Listen for 'Submit' events on the new palette button to sent a new network request to generate another random palette and update the rectangles, hex values, and gradient accordingly. 
- [x] Listen for `'submit'` events on the journal entry form and:
  - [x] Put the form's input values into a new object.
  - [x] Add the `nextEntryId` to the object.
  - [x] Increment the `nextEntryId` on the data model.
  - [x] Prepend the new object to the entries in the data model.
  - [x] Reset the form inputs.
  - [x] Generate a new random color palette
- [x] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new entry receives an incrementing `entryId`.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
