### ISSUE TITLE
Issue 2: User can search for a color palette

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/Pigment#2]
## 💰 Motivation

Users will want to search for a palette by specific colors they want to use 

## 📐 Plan

Create a search functionality that allows users to search for color palettes based on color 

## 🖼️ Wireframes
<img width="664" alt="Screen Shot 2022-08-02 at 6 50 22 PM" src="https://user-images.githubusercontent.com/106884008/182506862-5da20f7b-090c-4ab7-abda-f39bdb63bfb7.png">

<img width="699" alt="Screen Shot 2022-08-02 at 6 50 28 PM" src="https://user-images.githubusercontent.com/106884008/182506870-0aa907e2-2e5e-4a43-a1d2-aa3637f4f73a.png">

![Screen Shot 2022-08-02 at 6 52 42 PM](https://user-images.githubusercontent.com/106884008/182507098-56579d3e-9ad1-41f8-bdec-fd52c238c5d0.png)

![Screen Shot 2022-08-02 at 6 52 58 PM](https://user-images.githubusercontent.com/106884008/182507111-fe255332-6cbe-49cb-8696-5eb576224077.png)

## ✅ Task List

- [x] Add a color picker input to the form to allow the user to search for a palette by color. 
- [x] Add an event listener to the search input to save the users search
- [x] Create a function to convert the Hex code to RGB
- [x] Send a network request using the color parameters inputted by the users to generate the search result and update the palette on the page. 
- [x] Clean up all unnecessary styling. 
- [x] Test the app in private browsing 
- [x] Fix all errors
