### ISSUE TITLE
Issue 3: User can view their projects

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/Pigment#3]
## 💰 Motivation

Users will want to be able to see all their projects at once. 

## 📐 Plan

Allow users to view their entries. There's a snapshot view and a more comprehensive view. 

## 🖼️ Wireframes

![Screen Shot 2022-08-01 at 1 14 43 PM](https://user-images.githubusercontent.com/106884008/182237546-bab97a77-89bf-40ea-8057-99b898ef4bb7.png)
![Screen Shot 2022-08-01 at 1 13 28 PM](https://user-images.githubusercontent.com/106884008/182237111-de082ee8-6eba-47df-9ca0-db60a1c3945d.png)
![Screen Shot 2022-08-01 at 1 14 13 PM](https://user-images.githubusercontent.com/106884008/182237358-5419b010-685b-4269-b89f-e089e7c43d5d.png)

## ✅ Task List

- [x] Add an anchor element to the navigation bar for projects
- [x] Add a sibling `div[data-view="projects"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="projects"]` element in the HTML.
- [x] Add some dummy projects (snapshot view) to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the project list looks good on both mobile and desktop screens.
- [x] Create the modal that will display the full project details 
- [x] Define a function that generates the DOM tree for the project snapshots that matches one of the example project entries in the HTML.
- [x] Use a loop to create a DOM tree for each project entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Define a function to generate the DOM tree for the project details page 
- [x] Add an event listener to the three circles icon to show the modal and generate the DOM tree when it's clicked on 
- [x] Add an event listener to the x icon to close the modal when clicked on
- [x] Remove the example HTML projects once the user's projects are successfully being appended to the DOM on page load.
- [x] Add an event listener to the New anchor that shows the new projects page when it's clicked on
- [x] Add an event listener to the Projects anchor that shows the projects page when it's clicked on
- [x] Ensure that submitting a new project also creates a new DOM tree for it and adds it to the page.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
