### ISSUE TITLE
Issue 4: User can mark an entry as completed

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/Pigment#4]
## 💰 Motivation

User will want to indicate whether or not they completed a project

## 📐 Plan

All the user the ability to indicate that they project has been completed. 

## 🖼️ Wireframes

![Screen Shot 2022-08-01 at 1 16 53 PM](https://user-images.githubusercontent.com/106884008/182238336-ec7f2cbb-da77-4e62-b427-4d7cbc96bb57.png)
![Screen Shot 2022-08-01 at 1 17 07 PM](https://user-images.githubusercontent.com/106884008/182238391-4bce24f6-7adc-4704-8827-1b10407db73c.png)
![Screen Shot 2022-08-01 at 1 17 30 PM](https://user-images.githubusercontent.com/106884008/182238544-0629630b-d875-4ea2-8952-24f17b7e639c.png)
![Screen Shot 2022-08-01 at 1 17 47 PM](https://user-images.githubusercontent.com/106884008/182238635-a225b721-dda1-46c3-afb4-4c004fdac40e.png)

## ✅ Task List

- [x] Add a dummy html project entry. Add and style the checkmark. 
- [x] Revise the html to include an empty checkmark for the project details modal.
- [x] Update the function that generates the dom tree for each project entry to make an empty checkmark 
- [x] add a completed property to your entries and set it to false every time a new project is saved. 
- [x] Add an event listener to the checkmark to change to green (fill and stroke) when a user clicks on it. 
  - [x] change the completed property to True 
  - [x] Allow the user to toggle between clicking and un-clicking it.  
- [x] Test functionality 
- [x] Remove unnecessary styling 
- [x] Fix errors
