### ISSUE TITLE
Issue 5: User can edit their projects

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/Pigment#5]
## 💰 Motivation

User will want to edit their entries. 

## 📐 Plan

Allow the user the ability to updated their entries. 

## 🖼️ Wireframes

![Screen Shot 2022-08-01 at 1 19 50 PM](https://user-images.githubusercontent.com/106884008/182239386-3696db9c-f9e4-4a47-bf1d-bbf1127aa407.png)
![Screen Shot 2022-08-01 at 1 20 17 PM](https://user-images.githubusercontent.com/106884008/182239540-a3250874-51d9-481d-b2f1-91fb25093932.png)
![Screen Shot 2022-08-01 at 1 20 42 PM](https://user-images.githubusercontent.com/106884008/182239688-eadbe5f3-f75d-48d6-be9f-f5f6c94a21be.png)

![Screen Shot 2022-08-01 at 1 20 56 PM](https://user-images.githubusercontent.com/106884008/182239760-afff4662-500c-469a-866f-020ba3901362.png)

## ✅ Task List

- [x] Update html to do the following: 
  - [x] Add an edit icon to the polaroid 
  - [x] Add an edit icon to the modal  
- [x] Update the html for the entry form to reflect an edit form that adds a completed button to allow the user to indicate whether or not their form is completed. 
- [x] Add an editing property to the data model. 
- [x] Add an event listener to the edit icon on the modal and swap views to the form 
- [x] Update the polaroid clicks function to check if the click came from the edit icon. 
- [x]  Find the matching project (use entryId) in the data model and assign it to the data model's editing property.
- [x] Pre-populate the form with the clicked entry's values from the object found in the data model.
- [x] Update the form's header's text content to display "Edit Project"
- [x] Show the completed button on the form when in edit mode 
- [x] Update the form's submit handler function to conditionally add a new project or update the existing one.
- [x] Update the form's submit handler function to conditionally add a new entry DOM tree or replace the existing one.
- [x] Remove unnecessary CSS styling
- [x] Test functionality 
- [x] Fix errors
