### ISSUE TITLE
Issue 6: User can delete a project

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/Pigment#6]
## 💰 Motivation

User will want to remove a project if they are no longer going to complete it. 

## 📐 Plan

Allow the user the ability to delete a project. 

## 🖼️ Wireframes

![Screen Shot 2022-08-01 at 1 23 46 PM](https://user-images.githubusercontent.com/106884008/182240654-c8e7780e-a60c-4098-961d-e1342c06aa86.png)
![Screen Shot 2022-08-01 at 1 23 56 PM](https://user-images.githubusercontent.com/106884008/182240675-15637cbd-56b0-497c-aff9-b7912ba94410.png)

![Screen Shot 2022-08-01 at 1 24 18 PM](https://user-images.githubusercontent.com/106884008/182240727-ca150d7f-b54d-49de-ad30-a516f3151298.png)
![Screen Shot 2022-08-01 at 1 24 51 PM](https://user-images.githubusercontent.com/106884008/182240810-b98876f0-5ee6-4303-a5f6-9f882282708a.png)

## ✅ Task List

- [x]  Add a delete button to the form (only shows when the user clicks edit)
- [x]  Create a modal to confirm if the user wants to delete their entry 
- [x] Add an event listener for the delete button that shows the confirmation modal when clicked 
- [x] Hide the modal if the user clicks cancel. 
- [x] Remove the entry if the user confirms delete from the data model and from the page (delete it's DOM tree)
- [x] Once deleted, return back to the entries page. 
- [x] Test functionality 
- [x] Remove necessary CSS styling. 
- [x] Fix errors.
